<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_jKP8QLvoEfGmLL8pINuU7A" name="MiDiagrama" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_jKP8QbvoEfGmLL8pINuU7A" name="Diálisis Peritoneal Domiciliaria">
      <elements xmi:type="process:Lane" xmi:id="_jKP8QrvoEfGmLL8pINuU7A" name="Paciente / Cuidador Familiar " actor="_jKQjZLvoEfGmLL8pINuU7A">
        <elements xmi:type="process:StartEvent" xmi:id="_jKP8Q7voEfGmLL8pINuU7A" name="Inicio1" outgoing="_jKQjYbvoEfGmLL8pINuU7A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jKP8RLvoEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jKP8RbvoEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jKP8RrvoEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jKQjULvoEfGmLL8pINuU7A" name="Hola" incoming="_jKQjYbvoEfGmLL8pINuU7A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jKQjUbvoEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jKQjUrvoEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jKQjU7voEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jKQjVLvoEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jKQjVbvoEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jKQjVrvoEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jKQjV7voEfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jKQjWLvoEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jKQjWbvoEfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_jKQjWrvoEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jKQjW7voEfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jKQjXLvoEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gXCbgLvtEfG8mPXYfZvL2Q" name="Enfermería Nefrológica"/>
      <elements xmi:type="process:Lane" xmi:id="_EhXqQLvvEfGmLL8pINuU7A" name="Unidad de Diálisis">
        <elements xmi:type="process:StartEvent" xmi:id="_i78O8LvyEfGmLL8pINuU7A" name="Paciente con catéter peritoneal implantado">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i782ALvyEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i78O8bvyEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i782AbvyEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_L0sxILvzEfGmLL8pINuU7A" name="Instrucción del paciente en técnica manual (DCPA) o con cicladora (CDP)" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L0sxIrvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L0sxIbvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L0t_QLvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L0t_QbvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L0t_QrvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L0t_Q7vzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L0t_RbvzEfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L0t_RLvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_L0t_R7vzEfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_L0t_SLvzEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_L0t_RrvzEfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_L0t_SbvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_dAoRoLvzEfGmLL8pINuU7A" name="Realizar Test de Equilibrio Peritoneal (TEP) y pautar prescripción" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dAo4sbvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dAo4sLvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dAo4srvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dAo4s7vzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dAo4tLvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dAo4tbvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dAo4t7vzEfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dAo4trvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dAo4ubvzEfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_dAo4urvzEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dAo4uLvzEfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dAo4u7vzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_wosdYLvzEfGmLL8pINuU7A" name="Compuerta1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wosdYrvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wosdYbvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wosdY7vzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_2nEgULvzEfGmLL8pINuU7A" name="Esperar 1 mes">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2nEgUrvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2nEgUbvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2nEgU7vzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5E7p4LvzEfGmLL8pINuU7A" name="Valoración clínica presencial" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5E8Q8bvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5E8Q8LvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5E8Q8rvzEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5E8Q87vzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5E8Q9LvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5E8Q9bvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5E8Q97vzEfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5E8Q9rvzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5E8Q-bvzEfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_5E8Q-rvzEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5E8Q-LvzEfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5E8Q-7vzEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AYbFoLv0EfGmLL8pINuU7A" name="¿La técnica sigue siendo viable?">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AYbssbv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AYbssLv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AYbssrv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_MJ9aALv0EfGmLL8pINuU7A" name="Salida de Diálisis Peritoneal - Paso a Hemodiálisis">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MJ-oIbv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MJ-oILv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MJ-oIrv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UbrYkLv0EfGmLL8pINuU7A" name="Contactar telefónicamente con el paciente" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ubsmsbv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UbsmsLv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ubsmsrv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ubsms7v0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UbsmtLv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ubsmtbv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ubsmt7v0EfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ubsmtrv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Ubsmubv0EfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_Ubsmurv0EfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UbsmuLv0EfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Ubsmu7v0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dA7-MLv0EfGmLL8pINuU7A" name="¿Requiere revisión presencial urgente?">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dA8lQbv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dA8lQLv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dA8lQrv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ouUyYLv0EfGmLL8pINuU7A" name="Ajustar pauta de diálisis a distancia" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ouVZcbv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ouVZcLv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ouVZcrv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ouVZc7v0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ouVZdLv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ouVZdbv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ouVZd7v0EfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ouVZdrv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ouVZebv0EfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_ouVZerv0EfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ouVZeLv0EfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ouVZe7v0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_sGx78Lv0EfGmLL8pINuU7A" name="Citar al paciente en el hospital" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sGx78rv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sGx78bv0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sGx787v0EfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sGx79Lv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sGx79bv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sGx79rv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sGx7-Lv0EfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sGx797v0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_sGx7-rv0EfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_sGx7-7v0EfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_sGx7-bv0EfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_sGx7_Lv0EfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_jKQjXbvoEfGmLL8pINuU7A">
        <targetForm xmi:type="expression:Expression" xmi:id="_jKQjXrvoEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_jKQjX7voEfGmLL8pINuU7A">
        <targetForm xmi:type="expression:Expression" xmi:id="_jKQjYLvoEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jKQjYbvoEfGmLL8pINuU7A" target="_jKQjULvoEfGmLL8pINuU7A" source="_jKP8Q7voEfGmLL8pINuU7A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jKQjYrvoEfGmLL8pINuU7A"/>
        <condition xmi:type="expression:Expression" xmi:id="_jKQjY7voEfGmLL8pINuU7A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_jKQjZLvoEfGmLL8pINuU7A" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_jKQjZbvoEfGmLL8pINuU7A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jKQjZrvoEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_jKQjZ7voEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jKQjaLvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jKQjabvoEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_jKQjarvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jKQja7voEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jKQjbLvoEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_jKQjbbvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jKQjbrvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jKQjb7voEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_jKQjcLvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jKQjcbvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jKQjcrvoEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_jKQjc7voEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jKQjdLvoEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_jKQjdbvoEfGmLL8pINuU7A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_jKQjdrvoEfGmLL8pINuU7A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_jKQjd7voEfGmLL8pINuU7A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_jKQjeLvoEfGmLL8pINuU7A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_jKQjebvoEfGmLL8pINuU7A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_jKQjervoEfGmLL8pINuU7A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_jKQje7voEfGmLL8pINuU7A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_jKQjfLvoEfGmLL8pINuU7A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_jKQjfbvoEfGmLL8pINuU7A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_jKQjfrvoEfGmLL8pINuU7A" type="Process" element="_jKP8QLvoEfGmLL8pINuU7A" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_jKQjf7voEfGmLL8pINuU7A" type="2007" element="_jKP8QbvoEfGmLL8pINuU7A">
      <children xmi:type="notation:DecorationNode" xmi:id="_jKQjgLvoEfGmLL8pINuU7A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_jKQjgbvoEfGmLL8pINuU7A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_jKQjgrvoEfGmLL8pINuU7A" type="3007" element="_jKP8QrvoEfGmLL8pINuU7A">
          <children xmi:type="notation:DecorationNode" xmi:id="_jKQjg7voEfGmLL8pINuU7A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jKQjhLvoEfGmLL8pINuU7A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jKQjhbvoEfGmLL8pINuU7A" type="3005" element="_jKQjULvoEfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jKQjhrvoEfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jKQjh7voEfGmLL8pINuU7A" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jKQjiLvoEfGmLL8pINuU7A" type="3002" element="_jKP8Q7voEfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jKQjibvoEfGmLL8pINuU7A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jKQjirvoEfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jKQji7voEfGmLL8pINuU7A" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jKQjjLvoEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jKQjjbvoEfGmLL8pINuU7A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jKQjjrvoEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jKQjj7voEfGmLL8pINuU7A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jKQjkLvoEfGmLL8pINuU7A"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gXGs8LvtEfG8mPXYfZvL2Q" type="3007" element="_gXCbgLvtEfG8mPXYfZvL2Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_gXHUALvtEfG8mPXYfZvL2Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gXHUAbvtEfG8mPXYfZvL2Q" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gXGs8bvtEfG8mPXYfZvL2Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gXGs8rvtEfG8mPXYfZvL2Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gXGs87vtEfG8mPXYfZvL2Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gXHUArvtEfG8mPXYfZvL2Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gXGs9LvtEfG8mPXYfZvL2Q" x="48" y="250" width="777" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_EhZfcLvvEfGmLL8pINuU7A" type="3007" element="_EhXqQLvvEfGmLL8pINuU7A">
          <children xmi:type="notation:DecorationNode" xmi:id="_EhaGgLvvEfGmLL8pINuU7A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_EhaGgbvvEfGmLL8pINuU7A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_i79dELvyEfGmLL8pINuU7A" type="3002" element="_i78O8LvyEfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_i79dErvyEfGmLL8pINuU7A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_i7-EILvyEfGmLL8pINuU7A" x="81" y="23"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i79dEbvyEfGmLL8pINuU7A" x="60" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L0xpoLvzEfGmLL8pINuU7A" type="3005" element="_L0sxILvzEfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L0xporvzEfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L0xpobvzEfGmLL8pINuU7A" x="149" y="44" width="127" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dApfwLvzEfGmLL8pINuU7A" type="3005" element="_dAoRoLvzEfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dAqG0LvzEfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dApfwbvzEfGmLL8pINuU7A" x="309" y="36" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wotrgLvzEfGmLL8pINuU7A" type="3009" element="_wosdYLvzEfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wotrgrvzEfGmLL8pINuU7A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wotrg7vzEfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wotrgbvzEfGmLL8pINuU7A" x="498" y="54"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2nHjoLvzEfGmLL8pINuU7A" type="3017" element="_2nEgULvzEfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_2nHjorvzEfGmLL8pINuU7A" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2nHjo7vzEfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2nHjobvzEfGmLL8pINuU7A" x="593" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5E84ALvzEfGmLL8pINuU7A" type="3005" element="_5E7p4LvzEfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5E84ArvzEfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5E84AbvzEfGmLL8pINuU7A" x="649" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AYc60Lv0EfGmLL8pINuU7A" type="3008" element="_AYbFoLv0EfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_AYc60rv0EfGmLL8pINuU7A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_AYdh4Lv0EfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AYc60bv0EfGmLL8pINuU7A" x="783" y="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MJ_2QLv0EfGmLL8pINuU7A" type="3003" element="_MJ9aALv0EfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_MJ_2Qrv0EfGmLL8pINuU7A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MJ_2Q7v0EfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MJ_2Qbv0EfGmLL8pINuU7A" x="897" y="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UbtNwLv0EfGmLL8pINuU7A" type="3005" element="_UbrYkLv0EfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ubt00Lv0EfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UbtNwbv0EfGmLL8pINuU7A" x="1068" y="61" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dA-acLv0EfGmLL8pINuU7A" type="3008" element="_dA7-MLv0EfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dA-acrv0EfGmLL8pINuU7A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dA_BgLv0EfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dA-acbv0EfGmLL8pINuU7A" x="1239" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ouWAgLv0EfGmLL8pINuU7A" type="3005" element="_ouUyYLv0EfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ouWAgrv0EfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ouWAgbv0EfGmLL8pINuU7A" x="1391" y="36" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sGzKELv0EfGmLL8pINuU7A" type="3005" element="_sGx78Lv0EfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sGzKErv0EfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sGzKEbv0EfGmLL8pINuU7A" x="1411" y="139" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_EhZfcbvvEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_EhZfcrvvEfGmLL8pINuU7A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_EhZfc7vvEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_EhaGgrvvEfGmLL8pINuU7A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EhZfdLvvEfGmLL8pINuU7A" x="48" y="650" width="777" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_jKQjkbvoEfGmLL8pINuU7A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_jKQjkrvoEfGmLL8pINuU7A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_jKQjk7voEfGmLL8pINuU7A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_jKQjlLvoEfGmLL8pINuU7A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jKQjlbvoEfGmLL8pINuU7A" width="1700" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_jKQjlrvoEfGmLL8pINuU7A"/>
    <edges xmi:type="notation:Connector" xmi:id="_jKQjl7voEfGmLL8pINuU7A" type="4001" element="_jKQjYbvoEfGmLL8pINuU7A" source="_jKQjiLvoEfGmLL8pINuU7A" target="_jKQjhbvoEfGmLL8pINuU7A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jKQjmLvoEfGmLL8pINuU7A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jKQjmbvoEfGmLL8pINuU7A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jKQjmrvoEfGmLL8pINuU7A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jKQjm7voEfGmLL8pINuU7A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
