<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_XX4yYLvxEfGmLL8pINuU7A" name="MiDiagrama" version="2.0" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_XX4yYbvxEfGmLL8pINuU7A" name="Diálisis Peritoneal Domiciliaria" version="2.0">
      <elements xmi:type="process:Lane" xmi:id="_XX4yYrvxEfGmLL8pINuU7A" name="Paciente / Cuidador Familiar " actor="_XX4yfbvxEfGmLL8pINuU7A">
        <elements xmi:type="process:StartEvent" xmi:id="_XX4yY7vxEfGmLL8pINuU7A" name="Inicio1" outgoing="_XX4yervxEfGmLL8pINuU7A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XX4yZLvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XX4yZbvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XX4yZrvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_XX4yZ7vxEfGmLL8pINuU7A" name="PAPA" incoming="_XX4yervxEfGmLL8pINuU7A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XX4yaLvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XX4yabvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XX4yarvxEfGmLL8pINuU7A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XX4ya7vxEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XX4ybLvxEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XX4ybbvxEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XX4ybrvxEfGmLL8pINuU7A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XX4yb7vxEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XX4ycLvxEfGmLL8pINuU7A">
            <targetForm xmi:type="expression:Expression" xmi:id="_XX4ycbvxEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XX4ycrvxEfGmLL8pINuU7A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XX4yc7vxEfGmLL8pINuU7A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_XX4ydLvxEfGmLL8pINuU7A" name="Enfermería Nefrológica"/>
      <elements xmi:type="process:Lane" xmi:id="_XX4ydbvxEfGmLL8pINuU7A" name="Unidad de Diálisis"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_XX4ydrvxEfGmLL8pINuU7A">
        <targetForm xmi:type="expression:Expression" xmi:id="_XX4yd7vxEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_XX4yeLvxEfGmLL8pINuU7A">
        <targetForm xmi:type="expression:Expression" xmi:id="_XX4yebvxEfGmLL8pINuU7A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XX4yervxEfGmLL8pINuU7A" target="_XX4yZ7vxEfGmLL8pINuU7A" source="_XX4yY7vxEfGmLL8pINuU7A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XX4ye7vxEfGmLL8pINuU7A"/>
        <condition xmi:type="expression:Expression" xmi:id="_XX4yfLvxEfGmLL8pINuU7A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_XX4yfbvxEfGmLL8pINuU7A" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_XX4yfrvxEfGmLL8pINuU7A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XX4yf7vxEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_XX4ygLvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XX4ygbvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XX4ygrvxEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_XX4yg7vxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XX4yhLvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XX4yhbvxEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_XX4yhrvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XX4yh7vxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XX4yiLvxEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_XX4yibvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XX4yirvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XX4yi7vxEfGmLL8pINuU7A">
        <name xmi:type="expression:Expression" xmi:id="_XX4yjLvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XX4yjbvxEfGmLL8pINuU7A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_XX4yjrvxEfGmLL8pINuU7A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_XX4yj7vxEfGmLL8pINuU7A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_XX4ykLvxEfGmLL8pINuU7A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_XX4ykbvxEfGmLL8pINuU7A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_XX4ykrvxEfGmLL8pINuU7A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_XX4yk7vxEfGmLL8pINuU7A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_XX4ylLvxEfGmLL8pINuU7A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_XX4ylbvxEfGmLL8pINuU7A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_XX4ylrvxEfGmLL8pINuU7A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_XX4yl7vxEfGmLL8pINuU7A" type="Process" element="_XX4yYLvxEfGmLL8pINuU7A" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_XX4ymLvxEfGmLL8pINuU7A" type="2007" element="_XX4yYbvxEfGmLL8pINuU7A">
      <children xmi:type="notation:DecorationNode" xmi:id="_XX4ymbvxEfGmLL8pINuU7A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_XX4ymrvxEfGmLL8pINuU7A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_XX4ym7vxEfGmLL8pINuU7A" type="3007" element="_XX4yYrvxEfGmLL8pINuU7A">
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4ynLvxEfGmLL8pINuU7A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4ynbvxEfGmLL8pINuU7A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XX4ynrvxEfGmLL8pINuU7A" type="3005" element="_XX4yZ7vxEfGmLL8pINuU7A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XX4yn7vxEfGmLL8pINuU7A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4yoLvxEfGmLL8pINuU7A" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XX4yobvxEfGmLL8pINuU7A" type="3002" element="_XX4yY7vxEfGmLL8pINuU7A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XX4yorvxEfGmLL8pINuU7A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XX4yo7vxEfGmLL8pINuU7A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4ypLvxEfGmLL8pINuU7A" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XX4ypbvxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XX4yprvxEfGmLL8pINuU7A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XX4yp7vxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XX4yqLvxEfGmLL8pINuU7A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4yqbvxEfGmLL8pINuU7A"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_XX4yqrvxEfGmLL8pINuU7A" type="3007" element="_XX4ydLvxEfGmLL8pINuU7A">
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4yq7vxEfGmLL8pINuU7A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4yrLvxEfGmLL8pINuU7A" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XX4yrbvxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XX4yrrvxEfGmLL8pINuU7A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XX4yr7vxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XX4ysLvxEfGmLL8pINuU7A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4ysbvxEfGmLL8pINuU7A" x="48" y="250" width="777" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_XX4ysrvxEfGmLL8pINuU7A" type="3007" element="_XX4ydbvxEfGmLL8pINuU7A">
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4ys7vxEfGmLL8pINuU7A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XX4ytLvxEfGmLL8pINuU7A" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XX4ytbvxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XX4ytrvxEfGmLL8pINuU7A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XX4yt7vxEfGmLL8pINuU7A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XX4yuLvxEfGmLL8pINuU7A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4yubvxEfGmLL8pINuU7A" x="48" y="650" width="777" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_XX4yurvxEfGmLL8pINuU7A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_XX4yu7vxEfGmLL8pINuU7A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_XX4yvLvxEfGmLL8pINuU7A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_XX4yvbvxEfGmLL8pINuU7A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XX4yvrvxEfGmLL8pINuU7A" width="800" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_XX4yv7vxEfGmLL8pINuU7A"/>
    <edges xmi:type="notation:Connector" xmi:id="_XX4ywLvxEfGmLL8pINuU7A" type="4001" element="_XX4yervxEfGmLL8pINuU7A" source="_XX4yobvxEfGmLL8pINuU7A" target="_XX4ynrvxEfGmLL8pINuU7A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XX4ywbvxEfGmLL8pINuU7A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XX4ywrvxEfGmLL8pINuU7A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XX4yw7vxEfGmLL8pINuU7A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XX4yxLvxEfGmLL8pINuU7A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
